
rest.security.jwt:
  tokenExpirationTime: 60 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: tree_binary_api
  tokenSigningKey: pass12345
  
rest.security.web:
  pathWihtoutAuth: /api/**  
  tokenBasedAuthEntryPoint: /auth/**


spring:
  messages:
    basename: locale/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: true 


  
